### ISSUE TITLE
Bug in BufferedImage usage

### ISSUE THREAD

**Issue by hYdos** [Traneptora/jxlatte#17]
I'm not even sure how this happened, But your `BufferedImage` returned from `JxlImage` managed to crash `ComponenetColorModel` inside of AWT. 
![image](https://user-images.githubusercontent.com/25501603/232391121-920ce3c3-b1e3-469c-a40b-82a0d79e814d.png)
The call stack: 
![image](https://user-images.githubusercontent.com/25501603/232391233-930749fa-ec53-4747-ae2f-ae2309da78e4.png)
My Code running into the error:
![image](https://user-images.githubusercontent.com/25501603/232391412-b114f8e7-6b43-4245-bab3-62e9744b78a8.png)
Unfortunately, I cannot provide you with the image this time as its so messed up ImageIO cant find a way to encode the image
![image](https://user-images.githubusercontent.com/25501603/232391919-96905830-a504-41ee-ad53-6fa791c60533.png)
"Returns: false if no appropriate writer is found."

**Comment by hYdos** [comment]
Update: I did more digging and found the jxl file responsible
https://cdn.discordapp.com/attachments/1080332031914950716/1097396030779166820/body_a_mtl.jxl

**Comment by Traneptora** [comment]
If you're going to say "something crashed" then at the very least, provide a stack trace. What else do you expect me to do?

You should *not* expect ImageIO to be able to write the buffered image to PNG as its data type is DataBuffer.TYPE_FLOAT. You will need to draw it on another BufferedImage that the PNG writer understands. Alternatively, just write a PNG directly with the PNGWriter class provided by jxlatte.

**Comment by Traneptora** [comment]
That's not a stack trace.
