### ISSUE TITLE
Decompress 16-bit image back into 16 bit?

### ISSUE THREAD

**Issue by siiinc** [Traneptora/jxlatte#23]
Is there an option that will enable me to convert a compressed 16bit image (short) back to 16bits and not float?

**Comment by Traneptora** [comment]
`JXLImage` only supports floats. If you have a 16-bit RGB `BufferedImage` you can always do something like:
```
JXLImage jxlImage = decoder.decode();
BufferedImage my16bitImage = foo;
Graphics g = my16BitImage.createGraphics();
g.drawImage(jxlImage.asBufferedImage(), 0, 0, null);
```.

**Comment by siiinc** [comment]
I am not worried about the data type but is there a way to stop data rescaling? The image looks fine when displayed, just the pixel values, which mean something to me, a changed.

i.e., jxl pixels (via libjxl) as [245, 302, 394] becomes jxlatte decompressed [0.000289578107185662, 0.000356883567292243, 0.000465500168502331]

**Comment by Traneptora** [comment]
libjxl is using floats and it's just scaling it before giving it to you in an opaque way.

**Comment by siiinc** [comment]
Using com.thebombzen.jxlatte.io.PNGWriter as an example I was able to scale back to 16bit vals.
