### ISSUE TITLE
Kotlin Multiplatform?

### ISSUE THREAD

**Issue by StefanOltmann** [Traneptora/jxlatte#29]
What do you think about making this a Kotlin Multiplatform lib?

Quickly going over the code there seems to be nothing that requires this to be in Java.
BufferedImage can be replaced with Skiko, Charsets are supported by Ktor.

Kotlin and Java are very close and your lib would have a way broader reach while still having a JAR usable by plain Java projects. You can even target Windows and have an EXE.

**Comment by Traneptora** [comment]
Nothing requires it to be in java except the fact that the entire project is written in java and switching to another language would require a full rewrite. I don't understand what you are asking. 

Any application that targets the jvm can use jxlatte as a library.

**Comment by StefanOltmann** [comment]
No, it doesn’t require a full rewrite. It’s merely a matter of converting it in IntelliJ IDEA, which does a great deal of the job.

For Multiplatform Java libs need to replaced, but I don’t see that much here.

Come to the Kotlin side, we have cookies! 😉

**Comment by Traneptora** [comment]
Automatically converting the code to another language I don't know makes it entirely unmaintaintainable.

**Comment by Traneptora** [comment]
Also, this code doesn't use ImageIO to write PNGs.  I rolled my own.

**Comment by StefanOltmann** [comment]
I meant converting it to Kotlin and keeping it that way. So moving on from Java. This was just an idea.

By the time you have implemented the full feature set I may create a Kotlin fork to make it usable on all platforms like I did with Adobe XMP & Apache Commons Imaging before.
