### ISSUE TITLE
Using the latest code to display `sample/wb-rainbow.jxl`, the image seems to be incompletely displayed.

### ISSUE THREAD

**Issue by meiMingle** [Traneptora/jxlatte#30]
![image](https://github.com/Traneptora/jxlatte/assets/39942874/fefd3ded-26d8-4980-86a5-426ffb26af75)

**Comment by meiMingle** [comment]
What is certain is that it is attributed to CommitId:6d8b4c4 `prevent ballooning memory with hydrium encodes`

**Comment by Traneptora** [comment]
I believe I fixed it with 4712580549b72bc49fc6382182254cc96bb8fe3b.

**Comment by meiMingle** [comment]
Yes, now it works fine
