### ISSUE TITLE
Incorrect decoding of losslessly encoded images

### ISSUE THREAD

**Issue by jendalinda** [Traneptora/jxlatte#32]
Some losslessly encoed jxl files decode incorrectly, with incorrect colors and visible boundaries between parts of the image.

Example jxl file: [lena.zip](https://github.com/user-attachments/files/16426474/lena.zip)

![error](https://github.com/user-attachments/assets/df8ec34b-39c3-4b3a-a9cc-b5f3e9cd0460)

**Comment by Traneptora** [comment]
I can reproduce this. I suspect it's an RCT bug, will investigate more. Those are group boundaries.

**Comment by Traneptora** [comment]
Fixed by 6c1c07029ffe854f5953ed1c5b02fa58a0efccb8.
